---
- name: Manage OpenStack Networks
  hosts: control_node
  gather_facts: false
  become: false
  collections:
    - tok.openstack
    
  tasks:

    - name: Fetch subnets and store in register
      os_subnets_info:
        cloud: "{{ openstack_cloud }}"
        #name: "external*"
        name: "{{ network_prefix }}*"
      register: r_subnets
      vars:
        network_prefix: external

    - name: Debug subnets
      debug:
        var: r_subnets.openstack_subnets[0].name

    - name: Fetch subnets and store in register
      os_subnets_info:
        cloud: "{{ openstack_cloud }}"
        filters:
          name: '"external*:'
          # name: "external-52-118-31-0"
      register: r_subnet_filter

    - name: Debug subnets
      debug:
        var: r_subnet_filter.openstack_subnets[0].name

    - name: Hacky way to extract pre-named external subnet
      shell: "openstack subnet list | grep external | awk '{ print $4 }'"
      register: r_subnet_name

    - name: Debug subnets
      debug:
        var: r_subnet_name.stdout_lines[0]

...
